-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity densifyto64_biasefYi_rom is 
    generic(
             DWIDTH     : integer := 7; 
             AWIDTH     : integer := 6; 
             MEM_SIZE    : integer := 64
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of densifyto64_biasefYi_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "0010101", 1 => "0010000", 2 => "0001010", 3 => "0011000", 
    4 => "1110101", 5 => "1101110", 6 => "0000010", 7 => "0011000", 
    8 => "0010011", 9 => "1110101", 10 => "0000100", 11 => "0010101", 
    12 => "0011001", 13 => "1000111", 14 => "1010100", 15 => "1011011", 
    16 => "0000110", 17 => "1111010", 18 => "1111101", 19 => "0011110", 
    20 => "1111011", 21 => "0001110", 22 => "1010010", 23 => "0001000", 
    24 => "0101011", 25 => "1111100", 26 => "1110000", 27 => "0010010", 
    28 => "1101111", 29 => "1110100", 30 => "0000000", 31 => "0000001", 
    32 => "0100010", 33 => "1001110", 34 => "1010011", 35 => "0101110", 
    36 => "0100010", 37 => "1111111", 38 => "0101001", 39 => "1101110", 
    40 => "1010001", 41 => "1110111", 42 => "0000100", 43 => "0000001", 
    44 => "1110100", 45 => "1111000", 46 => "0000001", 47 => "0000101", 
    48 => "0000010", 49 => "0001011", 50 => "1111011", 51 => "1011000", 
    52 => "0100000", 53 => "0100110", 54 => "1000110", 55 => "0000010", 
    56 => "1101111", 57 => "0000100", 58 => "0010011", 59 => "1111011", 
    60 => "1101100", 61 => "0100001", 62 => "0010011", 63 => "1111110" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity densifyto64_biasefYi is
    generic (
        DataWidth : INTEGER := 7;
        AddressRange : INTEGER := 64;
        AddressWidth : INTEGER := 6);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of densifyto64_biasefYi is
    component densifyto64_biasefYi_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    densifyto64_biasefYi_rom_U :  component densifyto64_biasefYi_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


