// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// a
// 0x0000 : Control signals
//          bit 0  - ap_start (Read/Write/COH)
//          bit 1  - ap_done (Read/COR)
//          bit 2  - ap_idle (Read)
//          bit 3  - ap_ready (Read)
//          bit 7  - auto_restart (Read/Write)
//          others - reserved
// 0x0004 : Global Interrupt Enable Register
//          bit 0  - Global Interrupt Enable (Read/Write)
//          others - reserved
// 0x0008 : IP Interrupt Enable Register (Read/Write)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x000c : IP Interrupt Status Register (Read/TOW)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x0800 ~
// 0x0fff : Memory 'input_V' (1024 * 9b)
//          Word n : bit [ 8: 0] - input_V[2n]
//                   bit [24:16] - input_V[2n+1]
//                   others      - reserved
// 0x1000 ~
// 0x101f : Memory 'softmax_out_V' (10 * 9b)
//          Word n : bit [ 8: 0] - softmax_out_V[2n]
//                   bit [24:16] - softmax_out_V[2n+1]
//                   others      - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL            0x0000
#define XDEV_DIGITS_CLASSIFY_A_ADDR_GIE                0x0004
#define XDEV_DIGITS_CLASSIFY_A_ADDR_IER                0x0008
#define XDEV_DIGITS_CLASSIFY_A_ADDR_ISR                0x000c
#define XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE       0x0800
#define XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH       0x0fff
#define XDEV_DIGITS_CLASSIFY_A_WIDTH_INPUT_V           9
#define XDEV_DIGITS_CLASSIFY_A_DEPTH_INPUT_V           1024
#define XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE 0x1000
#define XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH 0x101f
#define XDEV_DIGITS_CLASSIFY_A_WIDTH_SOFTMAX_OUT_V     9
#define XDEV_DIGITS_CLASSIFY_A_DEPTH_SOFTMAX_OUT_V     10

