// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdev_digits_classify.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDev_digits_classify_CfgInitialize(XDev_digits_classify *InstancePtr, XDev_digits_classify_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->A_BaseAddress = ConfigPtr->A_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDev_digits_classify_Start(XDev_digits_classify *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL) & 0x80;
    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDev_digits_classify_IsDone(XDev_digits_classify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDev_digits_classify_IsIdle(XDev_digits_classify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDev_digits_classify_IsReady(XDev_digits_classify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDev_digits_classify_EnableAutoRestart(XDev_digits_classify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL, 0x80);
}

void XDev_digits_classify_DisableAutoRestart(XDev_digits_classify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_AP_CTRL, 0);
}

u32 XDev_digits_classify_Get_input_V_BaseAddress(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE);
}

u32 XDev_digits_classify_Get_input_V_HighAddress(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH);
}

u32 XDev_digits_classify_Get_input_V_TotalBytes(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + 1);
}

u32 XDev_digits_classify_Get_input_V_BitWidth(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDEV_DIGITS_CLASSIFY_A_WIDTH_INPUT_V;
}

u32 XDev_digits_classify_Get_input_V_Depth(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDEV_DIGITS_CLASSIFY_A_DEPTH_INPUT_V;
}

u32 XDev_digits_classify_Write_input_V_Words(XDev_digits_classify *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XDev_digits_classify_Read_input_V_Words(XDev_digits_classify *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XDev_digits_classify_Write_input_V_Bytes(XDev_digits_classify *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XDev_digits_classify_Read_input_V_Bytes(XDev_digits_classify *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_INPUT_V_BASE + offset + i);
    }
    return length;
}

u32 XDev_digits_classify_Get_softmax_out_V_BaseAddress(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE);
}

u32 XDev_digits_classify_Get_softmax_out_V_HighAddress(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH);
}

u32 XDev_digits_classify_Get_softmax_out_V_TotalBytes(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + 1);
}

u32 XDev_digits_classify_Get_softmax_out_V_BitWidth(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDEV_DIGITS_CLASSIFY_A_WIDTH_SOFTMAX_OUT_V;
}

u32 XDev_digits_classify_Get_softmax_out_V_Depth(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDEV_DIGITS_CLASSIFY_A_DEPTH_SOFTMAX_OUT_V;
}

u32 XDev_digits_classify_Write_softmax_out_V_Words(XDev_digits_classify *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XDev_digits_classify_Read_softmax_out_V_Words(XDev_digits_classify *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XDev_digits_classify_Write_softmax_out_V_Bytes(XDev_digits_classify *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XDev_digits_classify_Read_softmax_out_V_Bytes(XDev_digits_classify *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_HIGH - XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->A_BaseAddress + XDEV_DIGITS_CLASSIFY_A_ADDR_SOFTMAX_OUT_V_BASE + offset + i);
    }
    return length;
}

void XDev_digits_classify_InterruptGlobalEnable(XDev_digits_classify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_GIE, 1);
}

void XDev_digits_classify_InterruptGlobalDisable(XDev_digits_classify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_GIE, 0);
}

void XDev_digits_classify_InterruptEnable(XDev_digits_classify *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_IER);
    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_IER, Register | Mask);
}

void XDev_digits_classify_InterruptDisable(XDev_digits_classify *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_IER);
    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_IER, Register & (~Mask));
}

void XDev_digits_classify_InterruptClear(XDev_digits_classify *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDev_digits_classify_WriteReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_ISR, Mask);
}

u32 XDev_digits_classify_InterruptGetEnabled(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_IER);
}

u32 XDev_digits_classify_InterruptGetStatus(XDev_digits_classify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDev_digits_classify_ReadReg(InstancePtr->A_BaseAddress, XDEV_DIGITS_CLASSIFY_A_ADDR_ISR);
}

