// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __convolve_weights_cud_H__
#define __convolve_weights_cud_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct convolve_weights_cud_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 9;
  static const unsigned AddressRange = 175;
  static const unsigned AddressWidth = 8;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(convolve_weights_cud_ram) {
        ram[0] = "0b000000010";
        ram[1] = "0b000010101";
        ram[2] = "0b111100000";
        ram[3] = "0b101110101";
        ram[4] = "0b000000110";
        ram[5] = "0b001000000";
        ram[6] = "0b000111100";
        ram[7] = "0b000010101";
        ram[8] = "0b001001010";
        ram[9] = "0b110110101";
        ram[10] = "0b110001000";
        ram[11] = "0b000111001";
        ram[12] = "0b000111000";
        ram[13] = "0b000111001";
        ram[14] = "0b001000000";
        ram[15] = "0b000100101";
        ram[16] = "0b110011000";
        ram[17] = "0b110101000";
        ram[18] = "0b111111011";
        ram[19] = "0b000100000";
        ram[20] = "0b001000110";
        ram[21] = "0b000010100";
        ram[22] = "0b000000011";
        ram[23] = "0b110010111";
        ram[24] = "0b111001111";
        ram[25] = "0b000111010";
        ram[26] = "0b000111000";
        ram[27] = "0b000011111";
        ram[28] = "0b111110111";
        ram[29] = "0b110101101";
        ram[30] = "0b110101001";
        ram[31] = "0b111000100";
        ram[32] = "0b000111000";
        ram[33] = "0b000011010";
        ram[34] = "0b001100101";
        ram[35] = "0b111010010";
        ram[36] = "0b111000100";
        ram[37] = "0b001011010";
        ram[38] = "0b110000111";
        ram[39] = "0b001000100";
        ram[40] = "0b000101001";
        ram[41] = "0b000001111";
        ram[42] = "0b000110100";
        ram[43] = "0b000110111";
        ram[44] = "0b000100110";
        ram[45] = "0b110101111";
        ram[46] = "0b111101001";
        ram[47] = "0b000001011";
        ram[48] = "0b000010101";
        ram[49] = "0b000101110";
        ram[50] = "0b001001010";
        ram[51] = "0b000001100";
        ram[52] = "0b111001000";
        ram[53] = "0b000011111";
        ram[54] = "0b001000111";
        ram[55] = "0b001101101";
        ram[56] = "0b000101010";
        ram[57] = "0b000010010";
        ram[58] = "0b111010011";
        ram[59] = "0b111000100";
        ram[60] = "0b000000001";
        ram[61] = "0b000101100";
        ram[62] = "0b000110011";
        ram[63] = "0b111100111";
        ram[64] = "0b110111111";
        ram[65] = "0b110011111";
        ram[66] = "0b111011000";
        ram[67] = "0b000001110";
        ram[68] = "0b000110010";
        ram[69] = "0b000000111";
        ram[70] = "0b111011001";
        ram[71] = "0b110011110";
        ram[72] = "0b001011000";
        ram[73] = "0b110010010";
        ram[74] = "0b111110111";
        ram[75] = "0b111011100";
        ram[76] = "0b111100111";
        ram[77] = "0b000100011";
        ram[78] = "0b000001000";
        ram[79] = "0b001011111";
        ram[80] = "0b111000100";
        ram[81] = "0b000000100";
        ram[82] = "0b000000001";
        ram[83] = "0b000001000";
        ram[84] = "0b000100100";
        ram[85] = "0b001011100";
        ram[86] = "0b001100101";
        ram[87] = "0b111011100";
        ram[88] = "0b000001111";
        ram[89] = "0b111100011";
        ram[90] = "0b000100011";
        ram[91] = "0b000011001";
        ram[92] = "0b001011110";
        ram[93] = "0b001010110";
        ram[94] = "0b000000011";
        ram[95] = "0b000000000";
        ram[96] = "0b000010010";
        ram[97] = "0b111100111";
        ram[98] = "0b111110010";
        ram[99] = "0b111011100";
        ram[100] = "0b111111111";
        ram[101] = "0b001001110";
        ram[102] = "0b000010111";
        ram[103] = "0b000100010";
        ram[104] = "0b110110110";
        ram[105] = "0b111010110";
        ram[106] = "0b110111001";
        ram[107] = "0b000001100";
        ram[108] = "0b110111011";
        ram[109] = "0b000111100";
        ram[110] = "0b110110011";
        ram[111] = "0b101111101";
        ram[112] = "0b000101110";
        ram[113] = "0b111001111";
        ram[114] = "0b111111010";
        ram[115] = "0b111100001";
        ram[116] = "0b111110100";
        ram[117] = "0b111000111";
        ram[118] = "0b111011101";
        ram[119] = "0b000010000";
        ram[120] = "0b000011011";
        ram[121] = "0b000111011";
        ram[122] = "0b000011100";
        ram[123] = "0b000000011";
        ram[124] = "0b111001001";
        ram[125] = "0b110110111";
        ram[126] = "0b111101111";
        ram[127] = "0b000110010";
        ram[128] = "0b000011000";
        ram[129] = "0b000101111";
        ram[130] = "0b000010001";
        ram[131] = "0b111001111";
        ram[132] = "0b110010110";
        ram[133] = "0b111101111";
        ram[134] = "0b000110010";
        ram[135] = "0b000011101";
        ram[136] = "0b001100101";
        ram[137] = "0b000101001";
        ram[138] = "0b000001111";
        ram[139] = "0b110010110";
        ram[140] = "0b001000101";
        ram[141] = "0b110100000";
        ram[142] = "0b110100110";
        ram[143] = "0b000011010";
        ram[144] = "0b000010010";
        ram[145] = "0b111101101";
        ram[146] = "0b110101001";
        ram[147] = "0b000001101";
        ram[148] = "0b110100110";
        ram[149] = "0b111100100";
        ram[150] = "0b000111011";
        ram[151] = "0b000010000";
        ram[152] = "0b000000010";
        ram[153] = "0b110101011";
        ram[154] = "0b000110100";
        ram[155] = "0b000001001";
        ram[156] = "0b000010001";
        ram[157] = "0b001011011";
        ram[158] = "0b000101000";
        ram[159] = "0b111000101";
        ram[160] = "0b111000000";
        ram[161] = "0b000100100";
        ram[162] = "0b000111110";
        ram[163] = "0b000001101";
        ram[164] = "0b000101111";
        ram[165] = "0b000011011";
        ram[166] = "0b111101010";
        ram[167] = "0b111101110";
        ram[168] = "0b000110010";
        ram[169] = "0b000100110";
        ram[170] = "0b000110000";
        ram[171] = "0b001010011";
        ram[172] = "0b000111011";
        ram[173] = "0b111001000";
        ram[174] = "0b110110000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(convolve_weights_cud) {


static const unsigned DataWidth = 9;
static const unsigned AddressRange = 175;
static const unsigned AddressWidth = 8;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


convolve_weights_cud_ram* meminst;


SC_CTOR(convolve_weights_cud) {
meminst = new convolve_weights_cud_ram("convolve_weights_cud_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~convolve_weights_cud() {
    delete meminst;
}


};//endmodule
#endif
