// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __densifyto64_biasefYi_H__
#define __densifyto64_biasefYi_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct densifyto64_biasefYi_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 7;
  static const unsigned AddressRange = 64;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(densifyto64_biasefYi_ram) {
        ram[0] = "0b0010101";
        ram[1] = "0b0010000";
        ram[2] = "0b0001010";
        ram[3] = "0b0011000";
        ram[4] = "0b1110101";
        ram[5] = "0b1101110";
        ram[6] = "0b0000010";
        ram[7] = "0b0011000";
        ram[8] = "0b0010011";
        ram[9] = "0b1110101";
        ram[10] = "0b0000100";
        ram[11] = "0b0010101";
        ram[12] = "0b0011001";
        ram[13] = "0b1000111";
        ram[14] = "0b1010100";
        ram[15] = "0b1011011";
        ram[16] = "0b0000110";
        ram[17] = "0b1111010";
        ram[18] = "0b1111101";
        ram[19] = "0b0011110";
        ram[20] = "0b1111011";
        ram[21] = "0b0001110";
        ram[22] = "0b1010010";
        ram[23] = "0b0001000";
        ram[24] = "0b0101011";
        ram[25] = "0b1111100";
        ram[26] = "0b1110000";
        ram[27] = "0b0010010";
        ram[28] = "0b1101111";
        ram[29] = "0b1110100";
        ram[30] = "0b0000000";
        ram[31] = "0b0000001";
        ram[32] = "0b0100010";
        ram[33] = "0b1001110";
        ram[34] = "0b1010011";
        ram[35] = "0b0101110";
        ram[36] = "0b0100010";
        ram[37] = "0b1111111";
        ram[38] = "0b0101001";
        ram[39] = "0b1101110";
        ram[40] = "0b1010001";
        ram[41] = "0b1110111";
        ram[42] = "0b0000100";
        ram[43] = "0b0000001";
        ram[44] = "0b1110100";
        ram[45] = "0b1111000";
        ram[46] = "0b0000001";
        ram[47] = "0b0000101";
        ram[48] = "0b0000010";
        ram[49] = "0b0001011";
        ram[50] = "0b1111011";
        ram[51] = "0b1011000";
        ram[52] = "0b0100000";
        ram[53] = "0b0100110";
        ram[54] = "0b1000110";
        ram[55] = "0b0000010";
        ram[56] = "0b1101111";
        ram[57] = "0b0000100";
        ram[58] = "0b0010011";
        ram[59] = "0b1111011";
        ram[60] = "0b1101100";
        ram[61] = "0b0100001";
        ram[62] = "0b0010011";
        ram[63] = "0b1111110";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(densifyto64_biasefYi) {


static const unsigned DataWidth = 7;
static const unsigned AddressRange = 64;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


densifyto64_biasefYi_ram* meminst;


SC_CTOR(densifyto64_biasefYi) {
meminst = new densifyto64_biasefYi_ram("densifyto64_biasefYi_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~densifyto64_biasefYi() {
    delete meminst;
}


};//endmodule
#endif
